$parameters = @{
    ComputerName = "EDMSIIS","EDMSFISP1","EDMSIISP2","EDMSPRCP1","EDMSRDSP2","EDMSRDSP3","EDMSRDSP4","EDMSIISP3","EDMSIISD3","EDMSIISDEV","EDMSIISP1","EDMSMSSQLP3","EDMSMSSQLD3","EDMSMYSQL1","EDMSMYSQLP1","EDMSODBP1","EDMSENTP1","EDMSWEBP1","EDMSODBD1","EDMSENTD1","EDMSWEBD1"
    
    FilePath = "UpdateRelay.ps1"
  }
  Invoke-Command @parameters
